export const LABELS = {
  CONNECT_LABEL: "Connect Wallet",
  GIVE_SOL: "Give me SOL",
  FAUCET_INFO:
    "This faucet will help you fund your accounts outside of Solana main network.",
  ACCOUNT_FUNDED: "Account funded.",
  REPAY_QUESTION: "How much would you like to repay?",
  REPAY_ACTION: "Repay",
  RESERVE_STATUS_TITLE: "Reserve Status & Configuration",
  AUDIT_WARNING: "Oyster Lending is unaudited software. Use at your own risk.",
  MENU_HOME: "Home",
  MENU_DASHBOARD: "Dashboard",
  MENU_DEPOSIT: "Deposit",
  MENU_BORROW: "Borrow",
  MENU_FAUCET: "Faucet",
  APP_TITLE: "Oyster Lending",
  CONNECT_BUTTON: "Connect",
  WALLET_TOOLTIP: "Wallet public key",
  SETTINGS_TOOLTIP: "Settings",
  SELECT_COLLATERAL: "Select collateral account?",
  BORROW_QUESTION: "How much would you like to borrow?",
  BORROW_ACTION: "Borrow",
  TABLE_TITLE_ASSET: "Asset",
  TABLE_TITLE_LOAN_BALANCE: "Your loan balance",
  TABLE_TITLE_DEPOSIT_BALANCE: "Your deposit balance",
  TABLE_TITLE_APY: "APY",
  TABLE_TITLE_APR: "APR",
  TABLE_TITLE_BORROW_APR: "Borrow APR",
  TABLE_TITLE_DEPOSIT_APR: "Deposit APY",
  TABLE_TITLE_TOTAL_BORROWED: "Total Borrowed",
  TABLE_TITLE_MARKET_SIZE: "Market Size",
  TABLE_TITLE_ACTION: "Action",
  TABLE_TITLE_MAX_BORROW: "Available fro you",
  DASHBOARD_TITLE_LOANS: "Loans",
  DASHBOARD_TITLE_DEPOSITS: "Deposits",
  WITHDRAW_ACTION: "Withdraw",
  WITHDRAW_QUESTION: "How much would you like to withdraw?",
};
