export const LABELS = {
  CONNECT_LABEL: "Connect Wallet",
  GIVE_SOL: "Give me SOL",
  FAUCET_INFO: "This faucet will help you fund your accounts outside of Solana main network.",
  ACCOUNT_FUNDED: "Account funded.",
  REPAY_QUESTION: "How much would you like to repay?",
  REPAY_ACTION: "Repay",
  RESERVE_STATUS_TITLE: "Reserve Status &amp; Configuration",
  AUDIT_WARNING: "Oyster Lending is unaudited software. Use at your own risk.",
  MENU_HOME: "Home",
  MENU_DASHBOARD: "Dashboard",
  MENU_DEPOSIT: "Deposit",
  MENU_BORROW: "Borrow",
  MENU_FAUCET: "Faucet",
  APP_TITLE: "Oyster Lending",
  CONNECT_BUTTON: "Connect",
  WALLET_TOOLTIP: "Wallet public key",
  SETTINGS_TOOLTIP: "Settings",
  SELECT_COLLATERAL: "Select collateral account?",
  BORROW_QUESTION: "How much would you like to borrow?",
  BORROW_ACTION: "Borrow",
  TABLE_TITLE_ASSET: "Asset",
  TABLE_TITLE_LOAN_BALANCE: "Your loan balan",
  TABLE_TITLE_APY: "APY",
  TABLE_TITLE_ACTION: "Action",
  DASHBOARD_TITLE_LOANS: "Loans",
  DASHBOARD_TITLE_DEPOSITS: "Deposts",
  WITHDRAW_ACTION: "Withdraw",
  WITHDRAW_QUESTION: "How much would you like to withdraw?",
}