export const LABELS = {
  CONNECT_LABEL: 'Connect Wallet',
  AUDIT_WARNING:
    'Oyster is an unaudited software project used for internal purposes at the Solana Foundation. This app is not for public use.',
  FOOTER:
    'This page was produced by the Solana Foundation ("SF") for internal educational and inspiration purposes only. SF does not encourage, induce or sanction the deployment, integration or use of Oyster or any similar application (including its code) in violation of applicable laws or regulations and hereby prohibits any such deployment, integration or use. Anyone using this code or a derivation thereof must comply with applicable laws and regulations when releasing related software.',
  MENU_HOME: 'Proposals',
  NEW_PROPOSAL: 'New Proposal',
  MENU_DASHBOARD: 'Dashboard',
  APP_TITLE: 'Oyster Proposals',
  CONNECT_BUTTON: 'Connect',
  WALLET_TOOLTIP: 'Wallet public key',
  WALLET_BALANCE: 'Wallet balance',
  SETTINGS_TOOLTIP: 'Settings',
  DASHBOARD_INFO: 'Connect to a wallet to view proposals.',
  DESCRIPTION: 'Description',
  PROPOSAL: 'Proposal',
  NO_LOAD: 'Unable to load markdown. Click to view.',
  SIG_GIVEN: 'Sigs Given',
  VOTES_REQUIRED: "Votes Req'd",
  VOTES_CAST: 'Votes Cast',
  ADMIN_PANEL: 'Admin Panel',
  COPY_FAILED_ADDRESSES_TO_INPUT: 'Copy failed addresses to the input',
  COPY_FAILED_ADDRESSES_TO_CLIPBOARD: 'Copy failed addresses to clipboard',
  FAILED_SIGNERS_COPIED_TO_INPUT: 'Failed signers copied to input!',
  FAILED_SIGNERS_COPIED_TO_CLIPBOARD: 'Failed signers copied to clipboard!',
  COMMA_SEPARATED_KEYS: 'Comma separated base58 pubkeys',
  SIGNERS: 'Signers',
  ADD_SIGNERS: 'Add Signers',
};
