export const LABELS = {
  CONNECT_LABEL: 'Connect Wallet',
  AUDIT_WARNING:
    'Oyster is an unaudited software project used for internal purposes at the Solana Foundation. This app is not for public use.',
  FOOTER:
    'This page was produced by the Solana Foundation ("SF") for internal educational and inspiration purposes only. SF does not encourage, induce or sanction the deployment, integration or use of Oyster or any similar application (including its code) in violation of applicable laws or regulations and hereby prohibits any such deployment, integration or use. Anyone using this code or a derivation thereof must comply with applicable laws and regulations when releasing related software.',
  MENU_HOME: 'Proposals',
  NEW_PROPOSAL: 'New Proposal',
  MENU_DASHBOARD: 'Dashboard',
  APP_TITLE: 'Oyster Proposals',
  CONNECT_BUTTON: 'Connect',
  WALLET_TOOLTIP: 'Wallet public key',
  WALLET_BALANCE: 'Wallet balance',
  SETTINGS_TOOLTIP: 'Settings',
  DASHBOARD_INFO: 'Connect to a wallet to view proposals.',
  DESCRIPTION: 'Description',
  PROPOSAL: 'Proposal',
  NO_LOAD: 'Unable to load markdown. Click to view.',
  SIG_GIVEN: 'Sigs Given',
  VOTES_REQUIRED: "Votes Req'd",
  VOTES_CAST: 'Votes Cast',
  ADMIN_PANEL: 'Admin Panel',
  COPY_FAILED_ADDRESSES_TO_INPUT: 'Copy failed addresses to the input',
  COPY_FAILED_ADDRESSES_TO_CLIPBOARD: 'Copy failed addresses to clipboard',
  FAILED_SIGNERS_COPIED_TO_INPUT: 'Failed signers copied to input!',
  FAILED_SIGNERS_COPIED_TO_CLIPBOARD: 'Failed signers copied to clipboard!',
  FAILED_HOLDERS_COPIED_TO_INPUT:
    'Failed governance token holders copied to input!',
  FAILED_HOLDERS_COPIED_TO_CLIPBOARD:
    'Failed governance token holders copied to clipboard!',
  COMMA_SEPARATED_KEYS: 'Comma separated base58 pubkeys',
  SIGNERS: 'Signers',
  ADD_SIGNERS: 'Add Signers',
  ADMIN_ACCOUNT_NOT_DEFINED: 'Admin account is not defined',
  SIG_ACCOUNT_NOT_DEFINED: 'Signature account is not defined',
  ENTER_AT_LEAST_ONE_PUB_KEY: 'Please enter at least one pub key.',
  PUB_KEY_FAILED:
    " Pub key  failed. Please check your inspector tab for more information. We'll continue onward and add this to a list for you to re-upload in a later save.",
  ADD: 'Add',
  REMOVE: 'Remove',
  ADDING_OR_REMOVING: 'Type',
  ADDING_VOTES_TO_VOTER: 'Converting governance tokens to voting tokens',
  VOTES_ADDED: 'Governance tokens converted.',
  ADDING_GOVERNANCE_TOKENS: 'Adding governance tokens',
  PLEASE_WAIT: 'Please wait...',
  GOVERNANCE_TOKENS_ADDED: 'Governance tokens added.',
  NEW_VOTED_ACCOUNT_ADDED: 'New vote account added.',
  ADDING_NEW_VOTE_ACCOUNT: 'Adding new vote account...',
  TRANSACTION: 'Transaction - ',
  CANT_GIVE_ZERO_TOKENS: "Can't give zero tokens to a user!",
  BULK_TOKENS: 'Token Holders',
  COMMA_SEPARATED_KEYS_AND_VOTES:
    'base58 pubkey, vote count, base58 pubkey, vote count, ...',
  SINGLE_HOLDER: 'Token Holder',
  AMOUNT: 'Amount',
  SINGLE_KEY: 'base58 pubkey',
  TOKEN_MODE: 'Mode',
  BULK: 'Bulk',
  SINGLE: 'Single',
  ADD_GOVERNANCE_TOKENS: 'Add Governance Tokens',
  BURNING_VOTES: 'Burning your votes...',
  VOTES_BURNED: 'Votes burned',
  VOTE: 'Vote',
  EXECUTING: 'Executing...',
  EXECUTED: 'Executed.',
  WITHDRAWING_VOTING_TOKENS: 'Refunding voting tokens as Governance Tokens',
  TOKENS_WITHDRAWN: 'Voting tokens refunded as Governance Tokens',
  REGISTER_TO_VOTE: 'Register to Vote',
  CONFIRM: 'Confirm',
  CANCEL: 'Cancel',
  ADD_MORE_VOTES: 'Add More Votes',
};
